openapi: "3.1.0"
info:
  title: Todo AI Chatbot API
  version: "1.0.0"
  description: |
    Chat endpoints for the AI-powered task management assistant.
    All endpoints require Bearer token authentication (Better Auth JWT).
    The AI agent uses MCP tools to read and write tasks — users interact
    entirely through natural language.

servers:
  - url: https://zainubnazish-phase-three-huggies.hf.space
    description: HF Space (production)
  - url: http://localhost:8000
    description: Local development

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChatRequest:
      type: object
      required: [message]
      properties:
        message:
          type: string
          minLength: 1
          maxLength: 1000
          description: Natural language message from the user
          example: "Add buy groceries to my list"
        conversation_id:
          type: string
          format: uuid
          nullable: true
          description: UUID of existing conversation. Omit or null to start a new one.
          example: "a5308f26-45d4-470b-9e74-bfbeb000dc90"

    ToolCallResponse:
      type: object
      properties:
        tool_name:
          type: string
          description: Name of the MCP tool invoked
          example: "add_task"
        parameters:
          type: string
          description: JSON-encoded tool input parameters
          example: '{"title": "buy groceries", "user_id": "abc123"}'
        result:
          type: string
          description: JSON-encoded tool output
          example: '{"id": "uuid", "title": "buy groceries", "completed": false}'
        status:
          type: string
          enum: [success, error]
          description: Tool execution status

    ChatResponse:
      type: object
      required: [conversation_id, response, tool_calls]
      properties:
        conversation_id:
          type: string
          format: uuid
          description: UUID of the conversation (newly created if first message)
          example: "a5308f26-45d4-470b-9e74-bfbeb000dc90"
        response:
          type: string
          description: AI assistant's natural language reply
          example: "Done! I've added 'Buy groceries' to your task list."
        tool_calls:
          type: array
          items:
            $ref: "#/components/schemas/ToolCallResponse"
          description: MCP tool calls made during this response (may be empty)

    MessageResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        conversation_id:
          type: string
          format: uuid
        role:
          type: string
          enum: [user, assistant]
        content:
          type: string
        created_at:
          type: string
          format: date-time

    MessagesResponse:
      type: object
      properties:
        conversation_id:
          type: string
          format: uuid
        messages:
          type: array
          items:
            $ref: "#/components/schemas/MessageResponse"

    ConversationResponse:
      type: object
      properties:
        conversation_id:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
          nullable: true
        updated_at:
          type: string
          format: date-time
          nullable: true

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string

paths:
  /api/v1/users/{user_id}/chat:
    post:
      summary: Send a chat message
      description: |
        Send a natural language message to the AI assistant.
        - If `conversation_id` is null or omitted, a new conversation is created and its UUID is returned.
        - User message is persisted **before** the AI call (never lost on timeout).
        - The assistant may invoke MCP tools autonomously (add/list/complete/delete/update task)
          before generating a final natural-language response.
        - Both user and assistant messages are persisted after the AI responds.
      operationId: sendMessage
      tags: [Chat]
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: Authenticated user's ID (must match JWT sub claim)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatRequest"
            examples:
              new_conversation:
                summary: Start a new conversation
                value:
                  message: "Add buy groceries to my list"
              continue_conversation:
                summary: Continue an existing conversation
                value:
                  message: "I'm done with groceries"
                  conversation_id: "a5308f26-45d4-470b-9e74-bfbeb000dc90"
      responses:
        "200":
          description: AI assistant response with optional tool call details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatResponse"
        "400":
          description: Message is empty or whitespace-only
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Missing or invalid Bearer token
        "403":
          description: user_id in path does not match JWT sub claim
        "404":
          description: conversation_id not found or does not belong to this user
        "502":
          description: AI service (model or MCP subprocess) unavailable
        "503":
          description: Database not configured

  /api/v1/users/{user_id}/conversations:
    get:
      summary: Get most recent conversation
      description: Returns metadata for the user's most recently active conversation. Returns `conversation_id: null` if no conversations exist.
      operationId: getRecentConversation
      tags: [Chat]
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Most recent conversation, or conversation_id=null if none exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationResponse"
        "401":
          description: Missing or invalid Bearer token
        "403":
          description: Forbidden — user_id mismatch

  /api/v1/users/{user_id}/conversations/{conversation_id}/messages:
    get:
      summary: Get messages in a conversation
      description: Returns all messages in chronological order for the specified conversation. Used to restore chat history on page load.
      operationId: getConversationMessages
      tags: [Chat]
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Ordered list of messages in the conversation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessagesResponse"
        "401":
          description: Missing or invalid Bearer token
        "403":
          description: Forbidden
        "404":
          description: Conversation not found or does not belong to this user
