apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.frontendConfigName }}
  namespace: default
  labels:
    app: todo-frontend
data:
  NEXT_PUBLIC_API_URL: {{ .Values.configmap.apiUrl | quote }}
