apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: default
  labels:
    app: todo-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.frontend.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.frontendConfigName }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
              memory: {{ .Values.frontend.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
              memory: {{ .Values.frontend.resources.limits.memory | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.livenessProbe.path }}
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.readinessProbe.path }}
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
